name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-26
    timeout-minutes: 30
    env:
      DEVELOPER_DIR: "/Applications/Xcode_26.2.0.app/Contents/Developer"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Run Unit Tests
        run: swift test

      - name: Run UI Tests
        shell: bash
        run: |
          xcodebuild test \
            -project Examples/Examples.xcodeproj \
            -scheme Examples \
            -destination "platform=iOS Simulator,arch=arm64,name=iPhone 17,OS=26.2" \
            -maximum-concurrent-test-simulator-destinations 1 \
            -parallel-testing-enabled NO \
            -derivedDataPath DerivedData \
            -resultBundlePath TestResults/ui_test_result_bundle | \
            xcbeautify

      - name: Upload UI Test Result Bundle
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: ui-test-result-bundle
          path: TestResults/ui_test_result_bundle.xcresult
          if-no-files-found: warn
