name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-15
    timeout-minutes: 30
    env:
      DEVELOPER_DIR: "/Applications/Xcode_26.0.app/Contents/Developer"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project Examples/Examples.xcodeproj \
            -scheme Examples \
            -only-testing:WebUITests \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=26.0" \
            -derivedDataPath DerivedData \
            -resultBundlePath TestResults/unit_test_result_bundle | \
            xcbeautify && exit ${PIPESTATUS[0]}

      - name: Run UI Tests
        run: |
          xcodebuild test-without-building \
            -project Examples/Examples.xcodeproj \
            -scheme Examples \
            -only-testing:ExamplesUITests \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=26.0" \
            -derivedDataPath DerivedData \
            -resultBundlePath TestResults/ui_test_result_bundle | \
            xcbeautify && exit ${PIPESTATUS[0]}
